# Generated by Django 4.2.16 on 2026-08-06 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wilaya",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wilaya_id", models.IntegerField(unique=True)),
                ("name_ar", models.CharField(max_length=50)),
                ("name_fr", models.CharField(max_length=50)),
                ("has_stopdesk", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Wilaya",
                "verbose_name_plural": "Wilayas",
                "ordering": ["wilaya_id"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("cod", "الدفع عند الاستلام")], default="cod", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_type",
            field=models.CharField(
                choices=[("domicile", "توصيل منزلي"), ("stopdesk", "مكتب التوقف")],
                default="domicile",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="EcotrackShipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ecotrack_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "تم الإنشاء"),
                            ("pickup", "قيد الاستلام"),
                            ("in_transit", "في الطريق"),
                            ("delivered", "تم التوصيل"),
                            ("returned", "مرتجع"),
                            ("cancelled", "ملغي"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ecotrack_shipment",
                        to="store.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ecotrack Shipment",
                "verbose_name_plural": "Ecotrack Shipments",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="wilaya",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.wilaya",
            ),
        ),
        migrations.CreateModel(
            name="ShippingFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("livraison", "توصيل"),
                            ("recouvrement", "تحصيل"),
                            ("retour", "إرجاع"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tarif_domicile",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "tarif_stopdesk",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wilaya",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.wilaya"
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping Fee",
                "verbose_name_plural": "Shipping Fees",
                "unique_together": {("wilaya", "service_type")},
            },
        ),
    ]
