# Generated by Django 4.2.16 on 2026-08-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_wilaya_order_payment_method_order_shipping_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='wilaya',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='shippingfee',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='shippingfee',
            name='wilaya',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('digital', 'منتج رقمي')], default='digital', max_length=10),
        ),
        migrations.DeleteModel(
            name='EcotrackShipment',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='ShippingFee',
        ),
        migrations.DeleteModel(
            name='Wilaya',
        ),
    ]
