# Generated by Django 4.2.16 on 2026-07-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='serial',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
