# Generated by Django 4.2.16 on 2026-07-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='token_balance',
            field=models.IntegerField(default=0),
        ),
    ]
