# Generated by Django 4.2.16 on 2026-07-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_token_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='referral_earnings',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='total_referrals',
        ),
    ]
