# Generated by Django 4.2.16 on 2026-07-25 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0005_remove_customer_referral_earnings_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="البريد الإلكتروني",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="token_balance",
            field=models.PositiveIntegerField(default=0, verbose_name="رصيد التوكنز"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="accounts.customer",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="accounts.customer",
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["email"], name="accounts_cu_email_cc1dd9_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["phone"], name="accounts_cu_phone_106324_idx"),
        ),
    ]
