# Generated by Django 4.2.16 on 2026-07-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_transaction_options_customer_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="password_hash",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="كلمة المرور"
            ),
        ),
    ]
