# Generated by Django 4.2.16 on 2026-07-17 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_customer_pin_remove_customer_serial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=18, unique=True)),
                ('pin', models.CharField(max_length=4)),
                ('downloads_total', models.IntegerField()),
                ('downloads_used', models.IntegerField(default=0)),
                ('downloads_remaining', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_used_up', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer')),
            ],
            options={
                'verbose_name': 'Serial Key',
                'verbose_name_plural': 'Serial Keys',
            },
        ),
        migrations.CreateModel(
            name='SerialPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('downloads_limit', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Serial Package',
                'verbose_name_plural': 'Serial Packages',
            },
        ),
        migrations.CreateModel(
            name='SerialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('file_type', models.CharField(max_length=20)),
                ('downloads_before', models.IntegerField()),
                ('downloads_after', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('serial_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serials.serialkey')),
            ],
            options={
                'verbose_name': 'Serial Usage',
                'verbose_name_plural': 'Serial Usages',
            },
        ),
        migrations.AddField(
            model_name='serialkey',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serials.serialpackage'),
        ),
    ]
