# Generated by Django 4.2.16 on 2026-07-22 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serialkey',
            old_name='downloads_remaining',
            new_name='tokens_remaining',
        ),
        migrations.RenameField(
            model_name='serialkey',
            old_name='downloads_total',
            new_name='tokens_total',
        ),
        migrations.RenameField(
            model_name='serialkey',
            old_name='downloads_used',
            new_name='tokens_used',
        ),
        migrations.RenameField(
            model_name='serialpackage',
            old_name='downloads_limit',
            new_name='tokens_limit',
        ),
        migrations.RenameField(
            model_name='serialusage',
            old_name='downloads_after',
            new_name='tokens_after',
        ),
        migrations.RenameField(
            model_name='serialusage',
            old_name='downloads_before',
            new_name='tokens_before',
        ),
    ]
