# Generated by Django 4.2.16 on 2026-07-23 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customer_referral_earnings_and_more'),
        ('serials', '0002_rename_downloads_remaining_serialkey_tokens_remaining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialkey',
            name='pin',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='serialkey',
            name='serial_number',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='serialusage',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
    ]
