# Generated by Django 4.2.16 on 2026-08-06 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_customer_password_hash"),
        ("serials", "0003_alter_serialkey_pin_alter_serialkey_serial_number_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="serialusage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Serial Usage",
                "verbose_name_plural": "Serial Usages",
            },
        ),
        migrations.AddField(
            model_name="serialkey",
            name="payment_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Payment ID (Chargily)",
            ),
        ),
        migrations.AddField(
            model_name="serialusage",
            name="tokens_used",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="serialusage",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="serial_usages",
                to="accounts.customer",
            ),
        ),
        migrations.AlterField(
            model_name="serialusage",
            name="file_type",
            field=models.CharField(default="unknown", max_length=20),
        ),
        migrations.AlterField(
            model_name="serialusage",
            name="serial_key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usages",
                to="serials.serialkey",
            ),
        ),
        migrations.AddIndex(
            model_name="serialkey",
            index=models.Index(
                fields=["serial_number", "pin"], name="serials_ser_serial__d95dee_idx"
            ),
        ),
    ]
