# Generated by Django 4.2.16 on 2026-07-17 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TVBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'TV Brand',
                'verbose_name_plural': 'TV Brands',
            },
        ),
        migrations.CreateModel(
            name='TVModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(max_length=100)),
                ('chassis', models.CharField(blank=True, max_length=100, null=True)),
                ('screen_size', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='models/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.tvbrand')),
            ],
            options={
                'verbose_name': 'TV Model',
                'verbose_name_plural': 'TV Models',
                'unique_together': {('brand', 'model_number')},
            },
        ),
        migrations.CreateModel(
            name='Schematic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schematic_type', models.CharField(choices=[('power_supply', 'Power Supply'), ('main_board', 'Main Board'), ('t_con', 'T-Con'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='schematics/')),
                ('file_size', models.BigIntegerField(editable=False, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('downloads_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.tvmodel')),
            ],
            options={
                'verbose_name': 'Schematic',
                'verbose_name_plural': 'Schematics',
            },
        ),
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='firmware/')),
                ('file_size', models.BigIntegerField(editable=False, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('downloads_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.tvmodel')),
            ],
            options={
                'verbose_name': 'Firmware',
                'verbose_name_plural': 'Firmwares',
            },
        ),
    ]
