# Generated by Django 4.2.16 on 2026-07-26 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0006_alter_transaction_options_customer_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TVBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="brands/")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "TV Brand",
                "verbose_name_plural": "TV Brands",
            },
        ),
        migrations.CreateModel(
            name="Schematic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_number", models.CharField(max_length=100)),
                (
                    "schematic_type",
                    models.CharField(
                        choices=[
                            ("power_supply", "Power Supply"),
                            ("main_board", "Main Board"),
                            ("t_con", "T-Con"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="schematics/"),
                ),
                ("file_url", models.URLField(blank=True, max_length=500, null=True)),
                ("cloud_url", models.URLField(blank=True, max_length=500, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("token_cost", models.IntegerField(default=300)),
                ("downloads_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.tvbrand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schematic",
                "verbose_name_plural": "Schematics",
            },
        ),
        migrations.CreateModel(
            name="Firmware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_number", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=50)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="firmware/"),
                ),
                ("file_url", models.URLField(blank=True, max_length=500, null=True)),
                ("cloud_url", models.URLField(blank=True, max_length=500, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("token_cost", models.IntegerField(default=500)),
                ("downloads_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.tvbrand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Firmware",
                "verbose_name_plural": "Firmwares",
            },
        ),
        migrations.CreateModel(
            name="DownloadToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                ("file_url", models.URLField(max_length=500)),
                ("file_name", models.CharField(max_length=200)),
                ("used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.customer",
                    ),
                ),
            ],
        ),
    ]
