# Generated by Django 4.2.16 on 2026-07-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="firmware",
            name="file_size",
        ),
        migrations.RemoveField(
            model_name="schematic",
            name="file_size",
        ),
        migrations.AddField(
            model_name="firmware",
            name="cloud_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="firmware",
            name="file_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="schematic",
            name="cloud_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="schematic",
            name="file_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="firmware",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="firmware/"),
        ),
        migrations.AlterField(
            model_name="schematic",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="schematics/"),
        ),
    ]
