# Generated by Django 4.2.16 on 2026-07-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_firmware_file_size_remove_schematic_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmware',
            name='token_cost',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='schematic',
            name='token_cost',
            field=models.IntegerField(default=300),
        ),
    ]
