# Generated by Django 4.2.16 on 2026-07-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_firmware_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="firmware",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="firmware_images/"
            ),
        ),
        migrations.AddField(
            model_name="schematic",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="schematic_images/"
            ),
        ),
    ]
