# Generated by Django 4.2.16 on 2026-07-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_firmware_image_schematic_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="firmware",
            name="image",
        ),
        migrations.RemoveField(
            model_name="schematic",
            name="image",
        ),
        migrations.AddField(
            model_name="firmware",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="schematic",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
