# Generated by Django 4.2.16 on 2026-07-26 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_remove_firmware_image_remove_schematic_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="firmware",
            name="file",
        ),
        migrations.RemoveField(
            model_name="schematic",
            name="file",
        ),
    ]
